### ISSUE TITLE
TMT copies whole git repo even when --root was given with a subdirectory

### ISSUE THREAD

**Issue by happz** [psss/tmt#1016]
I have tests under `/server/tests/tmt`, and I call `tmt --root /server/tests/tmt ...` to run them. Unfortunately, `tmt` walks directory structure from `--root` up to git repo root directory, and copies this directory - `/` in my example - to guest, instead of expected `/server/tests/tmt`. This can (and does) result into considerable increase of size of copied data, since instead of just the tests, it's parent two levels up is copied, and it may include stuff like development environments, images, temporary files, logs, virutalenvs, `.tox` directories, and so on. In my current case, `/server/tests/tmt` is 28 kB, `/` 1.6 GB.

My /server/tests/tmt/default.fmf:

```shell
/artemis/server/tests/tmt $ find 
.
./default.fmf
./.fmf
./.fmf/version
./verify-20-GiB-root
./verify-20-GiB-root/main.fmf
./verify-20-GiB-root/test.sh
/artemis/server/tests/tmt $ 
```

```
/artemis/server/tests/tmp $ cat default.fmf 
summary: Guest tests
discover:
    how: fmf
execute:
    how: tmt
/artemis/server/tests/tmt $ 
```

```
$ tmt --root /artemis/server/tests/tmp run -vv --all tests --name verify-20-GiB-root provision --how connect --guest $IP report
```

`/var/tmp/tmt/run-001/default/discover/default/tests` then contains not `/artemis/server/tests/tmt`, but `/artemis`, tasking rsync with transfering 60000x more data.
