### ISSUE TITLE
Selecting tests by '.' in addition to filter is broken when multiple plans are selected

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#1045]
If tmt run selects multiple plans, `tests --name .` doesn't work well. However it does for single plan.
See bellow for reproducer - plans have same definition so they should pick same (single) test.

Compare
```
$ tmt run --rm discover -vv  tests --name . plans --name /plan/second
/var/tmp/tmt/run-176

/plan/second
    discover
        how: fmf
        directory: /home/lzachar/back_uped/Doing/tmt-discover-bug
        filter: tag:-foo&tag:-bar
        summary: 1 test selected
            /this/none

```
with
```
$ tmt run --rm discover -vv  tests --name .
/var/tmp/tmt/run-177

/plan/first
    discover
        how: fmf
        directory: /home/lzachar/back_uped/Doing/tmt-discover-bug
        filter: tag:-foo&tag:-bar
        summary: 1 test selected
            /this/none

/plan/second
    discover
        how: fmf
        directory: /home/lzachar/back_uped/Doing/tmt-discover-bug
        filter: tag:-foo&tag:-bar
        summary: 2 tests selected
            /other/none
            /this/none

```

I have structure like this
```
.
├── other
│   └── main.fmf
├── plan.fmf
└── this
    └── main.fmf
```
`main.fmf` are same and contain
```yaml
test: echo
/foo:
    tag: foo
/bar:
    tag: bar
/none:
```
`plan.fmf` contains
```yaml
execute:
    how: tmt
discover:
    how: fmf
    filter: "tag:-foo&tag:-bar"
/first:
/second:
```
