### ISSUE TITLE
Multihost HA guests need exposure to underlying virt name. 

### ISSUE THREAD

**Issue by cmackows** [psss/tmt#1136]
Currently the hostname is not same as kvm virt name. The HA fencing configuration needs to know the virtual machine name (-H below).  Can the virtual machine name be set using '-name:' ? Is it possible to expose the kvm machine name to all nodes in test plan?

In this case the fence agent is fence_xvm :
    '-H     Virtual machine (domain UUID or name) to fence'

[root@lvm-c2-node1 ~]# fence_xvm -o status -H lvm-c1-node1
Status: ON

[root@lvm-c2-node1 ~]# fence_xvm -o reboot -H lvm-c1-node1

**Comment by psss** [comment]
Currently the `virtual.testcloud` plugin of the `provision` step generates a random name based on the run id. Here's an example `guests.yaml` file:

```yaml
default:
    guest: 127.0.0.1
    port: 10027
    user: root
    key: /var/tmp/tmt/run-178/plans/default/provision/default/id_ecdsa
    instance: tmt-178-FaLneNNm
    image: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images
    connection: session
```

The output of `virsh list` is as follows:

```
 Id    Name               State
-----------------------------------
 154   tmt-178-FaLneNNm   running
```

@cmackows, so you suggest that the `instance` name is exactly the same as the `name` key of the `provision` step config? @frantisekz, are there any limitations for the virt name? I guess we would have to replace any special chars, such as spaces, by `-` or similar.

**Comment by cmackows** [comment]
> @cmackows, so you suggest that the `instance` name is exactly the same as the `name` key of the `provision` step config?
@psss:  For our use cases, yes that would be helpful

**Comment by psss** [comment]
As discussed on today's meeting it would be possible to assign the instance names as need either based on the `name` key or another dedicated key, but the important point is that this functionality would be available only in the `virtual` provision method provided by the `testcloud` plugin. When run in the Testing Farm virtual machine names will not be available. We need to clarify expectations.

**Comment by psss** [comment]
@cmackows, one more idea: As a temporary/quick workaround you could also use the `guests.yaml` file which is already now available on all guests:

```yaml
# cat ../provision/guests.yaml
server:
    guest: 192.168.122.224
    port: 22
    user: root
    key: /var/tmp/tmt/run-203/plan/provision/server/id_ecdsa
    instance: tmt-203-xSmrcGpE
    image: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2
    connection: system
    arch: x86_64
client-one:
    guest: 192.168.122.189
    port: 22
    user: root
    key: /var/tmp/tmt/run-203/plan/provision/client-one/id_ecdsa
    role: client
    instance: tmt-203-nbguMqRZ
    image: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2
    connection: system
    arch: x86_64
client-two:
    guest: 192.168.122.83
    port: 22
    user: root
    key: /var/tmp/tmt/run-203/plan/provision/client-two/id_ecdsa
    role: client
    instance: tmt-203-TfKnkskE
    image: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2
    connection: system
    arch: x86_64
```

You could easily parse the `yaml` file and extract `instance` name for each guest and use it in the resource file. What do you think? Would it be worth trying?
