### ISSUE TITLE
HW requirements - disk partitions

### ISSUE THREAD

**Issue by kokesak** [psss/tmt#1243]
In `convert2rhel` and in `leapp` we have some old beaker tests that specifies the partitions that has to be created on the machine before running the tests.

We would like to specify the size of the partition, it's name, and the type whether it use regular standard partitioning or the LVM file system.

Example of the needed specification can be found [here](https://beaker-project.org/docs/user-guide/customizing-partitions.html).

Perhaps, extending the functionality of the multiple disks intrudced in #893 can be used?
```yml
---

disk:
  - space: ">= 20 GB"
  - partition:
      name: "/var"
      size: "10 GB"
      type: "LVM"
  - partition:
      - name: "/var/log"
      - size: "5 GB"
      - type: "LVM"
```

Also there is a specific case, where we want to test a monolithic root partition. Everything is stored inside the root `/` partition and no `swap` is created.
