### ISSUE TITLE
discover:how value is lost for child plans

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#127]
My goal is to have how:fmf in parent and just modify the filter for each child.

I have following plan
```yaml
summary: Run test with environment
discover:
    how: fmf
execute:
    how: beakerlib

/first:
    discover:
        filter: "component:python-requests"
/second:
```
When I run `tmt discover` I end up with
```
/var/tmp/tmt/run-071

/r/first
    discover
        how: shell
        tests: 0 tests selected

/r/second
    discover
        how: fmf
        directory: /home/lzachar/_important_/Tests/python-requests
        tests: 12 tests selected
```
See that /r/first has how: shell
