### ISSUE TITLE
Document discover methods in more detail

### ISSUE THREAD

**Issue by psss** [psss/tmt#165]
Let's add a bit more detailed information about the discover step both to the step [specification](https://tmt.readthedocs.io/en/latest/spec/steps.html#discover) and usage [examples](https://tmt.readthedocs.io/en/latest/examples.html#plans).

For example, we're completely missing manual test list:

```yaml
discover:
    how: shell
    tests:
    - name: /help/smoke
      test: ./smoke.sh
      path: /tests/shell
```
