### ISSUE TITLE
Define setup and cleanup code to be executed for each test

### ISSUE THREAD

**Issue by pellecchialuigi** [psss/tmt#2132]
I faced a scenario where I need to execute setup and cleanup code just before and after each test execution.
It will be of great help to be able to configure the above mentioned code from the tmt plan itself and to be able to skip it from the test fmf file if for some reason the logic is not applicable to one or few tests.
This is just a possible approach to the problem. Let see if there is any other solutions!

**Comment by psss** [comment]
@pellecchialuigi, sorry for the late response. Seems like this functionality would be quite close to the test checks?

* https://tmt.readthedocs.io/en/stable/plugins/test-checks.html

They can run actions before and after the individual test execution. But here it would be upon user to define the exact actions, right?

@happz, would it make sense to introduce a new test check with custom commands? The config could look like this:

```yaml
check:
    how: custom
    before-script: ./do-something-before.sh
    after-script: ./do-something-after.sh
```

Just brainstorming...
