### ISSUE TITLE
`tmt tests export --nitrate --create` removes virtual case from fmf file

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#238]
At first I had main.fmf like this
```yaml
summary: Some text
contact: my@email.com
component: [ package ]
test: ./test.sh
environment:
    FOO: bar

/additional:
    environment:
        key: value
```
I've run `tmt tests export --nitrate --create` so two cases are created in the nitrate.
But tmt removed virtual case from the fmf file and created just first case (and didn't link it to general plan)
After execution the main.fmf is as following:
```yaml
summary: Some text
contact: my@email.com
component: [ package ]
test: ./test.sh
environment:
    FOO: bar
extra-nitrate: TC#0607295
```
