### ISSUE TITLE
Provision a guest with multiple disks

### ISSUE THREAD

**Issue by guazhang** [psss/tmt#2536]
we need multiple disks server for some testing, like raid.    
but looks tmt don't support it, so could we add this function in provision ?

maybe like --hardware "disk.size >= 500GB"  --hardware "disk.count >= 4"

**Comment by happz** [comment]
Possible workaround:

```yaml
disk:
  - size: ">= 0"
  - size: ">= 0"
  - size: ">= 0"
  - size: ">= 0"
```

This would turn into requesting 4 disks of any size.
