### ISSUE TITLE
Allow environment definition per phase

### ISSUE THREAD

**Issue by kkaarreell** [psss/tmt#2714]
Sometimes it would be handy to be able to use something like this:
```
environment:
  MYVAR: value

discover:
  - name: part1
    url: https:/some/path
    test:
      - /test1
    environment:
      EXTRAVAR: part1

  - name: part2
    url: https:/some/path
    test:
      - /test1
    environment:
      EXTRAVAR: part2
```

Not sure ATM it if would make sense to request similar thing for context. Maybe just because plugins like reportportal could utilize such a context definition in RP reporting.

**Comment by lukaszachy** [comment]
Just a note about the proposal to edit discovered test metadata via https://github.com/teemtee/tmt/discussions/2430

However the above doesn't solve 'prepare' and 'finish' phases.

**Comment by psss** [comment]
The use case described in the issue description can be covered by using the `adjust-tests` key. Here's a working example:

```yaml
/plan:
    discover:
      - how: fmf
        adjust-tests:
            environment+:
                var: first
      - how: fmf
        adjust-tests:
            environment+:
                var: second
    provision:
        how: local
    execute: 
        how: tmt

/test:
    test: echo $var
```

@kkaarreell, is your use case covered well or should a similar functionality be added to the `prepare` and `finish` step as well as mentioned above by @lukaszachy?
