### ISSUE TITLE
Automated plan split into subplans

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#308]
Use case 1: Plan contain mutually exclusive tests, tmt should run distinct sets of tests separately
Use case 2: Each plan should be run multiple times with slightly modified environment

UC1: Test attributes as following should cause only equivalent tests to be run in same sub plan
* Hardware (min/max memory, CPU count...) requirement conflicts
* Additional repositories for require/recommend containing unsupported/not shipped packages - test contains metadata representing this fact.

UC2: Run plan "normally" as well as with FIPS mode enabled. Set of tests might be further pruned using relevancy.

It would be great if TMT allows sub-plans generation based on various attributes/plugins and each of them could be individually turn on/off.

**Comment by pvalena** [comment]
The `automated` part aside which will be deduced from L1 (and therefore kind-of hackish), when gathered the conflicting requirements, there should be some resul / definition for L2, right?.

Manually, If I wanted to say I want to say in my L2 metadata, while trying to be most specfiic, what should be the actual "split"?

Would it look something like this?

```yaml
prepare:
    split_plan:
        - repo: http://.......
provision:
    split_plan:
        - fips: enabled
        - cpu: [ 1, 2 ]
        - how: [ container, virtual ]     # (just some theoretical example)
```

So with each entry, the plan would "duplicate" into two, like so:

  - `with` and `without` the repository enabled
  - `with` and `without` the FIPS enabled
  -  with `1` and `2` CPUs
  - and _maybe_ with 2 different provisioners

Would that make sense? Or do you have some completely different approach in mind?

How would `UC 1` fit into this? Would there be some additional `filtering`, based on the requirements? 

_ _ _ _
Thinking about this I see 2 distinct behaviours: `split_plan` (__UC1__: the tests won't be same in the two) and `duplicate_plan` (__UC2__: the tests will be completely same). This also affects how the results will be gathered / merged / reported etc..

**Comment by psss** [comment]
Recently @fernflower shared with us a related use case for splitting plans per test:

 * Each test executed separately on a dedicated (clean) guest
 * Test results aggregated from all executed plans

I propose to start with covering this use case as the first step for automated plan generation. The config could look like this:

```yaml
discover:
    how: fmf
    slice: 1
```

Any better name for the option? The `slice` is coming from `wow` syntax. Perhaps use `split` instead? Or something like `split-plan` dictionary proposed above by @pvalena?

The question is into which step config it should go. Probably under the `discover` step as it is closely related to individual tests? Or under `execute`? Or even introduce a new config section for options which are not exactly related to a single step?

@lukaszachy, @thrix, @pvalena, @sopos, @jscotka, @fernflower, please share your thoughts.

**Comment by sopos** [comment]
It is still questionable where (in which step) the test set manipulation should be done. I will propagate my earlier idea of adding a new step which would be dedicated to various manipulations.
So in the _discover_ step, there woudl be tests gathered as usual and them there would be a modular step which would cut it based on various rules, e.g. simply slice, or group by common HW required, ...

**Comment by pvalena** [comment]
Actually, I think we have the manually enumerated variants solved via inheritance quite well, and I would rather avoid introducing another syntax.

To take the earlier example:
```yaml
prepare:
    [ . . . ]
execute:
    [ . . . ]

# maybe this isn't valid syntax. Sorry, writing this from the top of my head.
/fips-enabled
    provision:
        - how: virtual
          fips: enabled

/single-cpu
    provision:
        - how: virtual
          cpu: 1

/double-cpu
    provision:
        - how: virtual
          cpu: 2

/container-provision
    provision:
        - how: container
```
IOW I retract my earlier proposal for lists / split_plan.
_ _ _ _ 
 It doesn't cover `slicing` (generating multiple plans from tests), but I think that's a separate issue, which requires autogenerating / special handling (theoretically, you could write them manually as well, but I don't think that would be feasible/usable).

 +1 for `slice` for me. I'd prefer having it in `execute`,which seems kind-of intuitive (like execute tests "in isolation"); and we don't have many options in there currently:), but I would rather avoid creating another "step", unless it can be accomodated in other way (what would it "do", apart from managing other steps?).
