### ISSUE TITLE
Suggest using `./test.sh` for local test scripts

### ISSUE THREAD

**Issue by hadess** [psss/tmt#3703]
`tmt` can't find script relative to test manifest.

In `tests/tests.fmf`:
```
summary: Check basic command line options
discover:
    how: shell
execute:
    script: run_tests.sh
```

`tests/run_tests.sh` exists, but `tmt` complained about it not being found.

tmt should definitely look for tests relative to the test manifest before it tries to find them relative to the root of the repository.
