### ISSUE TITLE
Unclear that the execute step is mandatory when using test discovery

### ISSUE THREAD

**Issue by ekohl** [psss/tmt#3808]
I was very unfamiliar with tmt and exploring the discover plugin. After looking at https://tmt.readthedocs.io/en/stable/plugins/discover.html I assumed that I no longer needed to specify `execute` because that was already in the other tests.

Reproducer:

* Run `tmt init -t mini`
* Use the plan below

```yaml
summary: Basic smoke test
discover:
  - how: fmf
    test: /install
```

Now when you run `tmt plans ls` it doesn't show up. When I add an execute step it does:

```yaml
summary: Basic smoke test
discover:
  - how: fmf
    test: /install
execute:
  how: tmt
```

For me it was difficult to figure out why it didn't show up. I looked for some debug option of how it was parsing the plans, but couldn't see that.

One option may be to make it the default, but I can't judge if that makes sense.
