### ISSUE TITLE
Allow test selection using a shell script

### ISSUE THREAD

**Issue by psss** [psss/tmt#411]
@bachradsusi shared an interesting use case: In the selinux tests repository they are using a [shell script](https://src.fedoraproject.org/tests/selinux/blob/master/f/tests-pr.yml) to pick only those tests which have been modified by the pull request:

```ansible
- name: Generate list of tests in this PR
  shell: |
      git log --format= --stat --name-only origin/master..HEAD | sed '/\//!d;s#\(.*\)/.*#\1#' | sort -u | xargs
  delegate_to: localhost
  register: tests_list
```

It would be nice to provide a similar functionality in the discover step. Currently we support selecting tests by name or filter:

```yaml
discover:
    how: fmf
    test: /tests/basic
    filter: 'tier: 1'
```

We could also support executing a shell script instead:

```yaml
discover:
    how: fmf
    test: shell(git log...)
    filter: 'tier: 1'
```

This brings, however, a similar question about security as mentioned in #373.
