### ISSUE TITLE
tmt finish should run in the same folder as execute

### ISSUE THREAD

**Issue by thrix** [psss/tmt#423]
Finish step is there to for cleanup, but it runs in its own directory. One would expect this just to work

```
execute:
    how: shell
    script:
        - touch testik

finish:
    how: shell
    script:
        - rm testik
```

Seems just running in `execute` folder would make most sense, in case there is just one plan, run directly in the plan directory. I have no better idea right now.

Related to: https://github.com/fedora-ci/rpminspect-pipeline/pull/8
