### ISSUE TITLE
Can't access correct directory when in `prepare` when using `-h shell`

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#497]
I think this affects only `virtual` provisioning. The container works fine for me.

I run the test, with prepare -h shell and some script. It relies on the current directory, as I need to access local files from the script (the script itself is unerelevant; I could paste the code instead).

Example, not tested:
```yaml

prepare:
    - name: this does not work in VM
      script: ls ../discover/default/tests/

```

If I access the failed run (I've run it with `--skip finish`), and run the EXACT command that's in `prepare`, it succeeds:

```console
$ tmt run -l login -s prepare:start
[root@testcloud prepare]# ls ../discover/default/tests/
 -> ok
```

Full log: https://git.io/JLBBe
(in log, the first `login` fails with `--when error --when failure`, but that's a separate issue)
