### ISSUE TITLE
RFE: prepare part for each step in plan

### ISSUE THREAD

**Issue by jscotka** [psss/tmt#588]
I had trouble with order of commands that `prepare` is done after `discovery`. (Or better to say, it is clear, that `prepare` is executed on target machine but not so clean that `discovery` not and order of these commands ). It would good to do some steps before discovery.

My usecase is, that I have no FMF data for tests, just plan, and tests metadata are automatically generated from python decorators. So that I had to run my tool what generates them, and discovery is done before it tries to do that. and do not want to store these automatically generated fmf files inside git, as potentialy of out of sync.

as we've discussed with @lukaszachy it probably makes sense that each `step` could have some possibility to run some setup before running the rest, some `setup` or `assemble` attribute with same syntax like current `prepare` (or maybe allow just script?)

### syntax could be like
```
discover:
    setup: (do commands on host machine if discover is done on host)
       - name: install deps on host
         how: install
         packages:
            a
            b
        - name: generate fmf data
          script: ./path/to/script
    how: fmf
execute:
    setup: (do commands on guest machine)
      ... 
    how: tmt

```

### My current plan
It expected that prepare is before discovery (and expected that discovery is also done on target machine)
```
summary: Run browser integration tests on the host
prepare:
  - name: Install cockpit and test dependencies
    how: install
    package:
    - cockpit
    - cockpit-ws
    - cockpit-system
    - cockpit-bridge
    - git
    - libvirt-python3
    - make
    - npm
    - python3
  - name: Install Chromium
    script: ./plans/prepare-chromium.sh
  - name: Create users for tests
    script: ./plans/prepare-users.sh
  - name: Start cockpit service & generic hacks
    script: ./plans/prepare-generic.sh
  - name: Regenerate fmf data for tests form python files
    script: ./plans/prepare-fmf-regeneration.sh
discover:
  how: fmf
  test: [/verify/check-testlib/TestRunTestListing/testBasic]
execute:
  how: tmt
```
