### ISSUE TITLE
prepare step fails with cryptic error if ansible playbook is run against a vm with root auth disabled

### ISSUE THREAD

**Issue by fernflower** [psss/tmt#601]
Steps to reproduce:
1. Vm with root auth disabled (like vanilla cloud rhel7.9 image, discovered with latest openstack rhel7.9 image)
2. `tmt run -a provision  -h connect -g YOUR_VM_IP_HERE `

This will fail with cryptic 
```
protocol version mismatch -- is your shell clean?
 
Failed to run command 'rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/ivasilev/.ssh/id_rsa" --safe-links /var/tmp/tmt/run-021/plans/integration root@10.0.79.174:/'.
```

If step 2 is run with user specified like `tmt run -a provision  -h connect -g 10.0.79.174 --user cloud-user` or the rsync command is executed manually as 
```
rsync -Rrz --links --safe-links --delete -e "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/ivasilev/.ssh/id_rsa" --safe-links /var/tmp/tmt/run-021/plans/integration cloud-user@10.0.79.174:/ 
```
 the issue is not there.

**Comment by fernflower** [comment]
Just for the sake of clarity - the test plan that was run
```
summary: Basic smoke test
execute:
    how: tmt
discover:
    name: tier42
    how: fmf
    filter: 'tier: jats'
provision:
    how: connect
    guest: 10.0.79.250
    key: /home/ivasilev/.ssh/id_rsa

prepare:
    how: ansible
    playbook: /home/ivasilev/automateit/leapp_with_tests.yml
```
