### ISSUE TITLE
Strip .git from github.com URL for libraries (any repo from github)

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#614]
If plan contains mixture of 'library()' and direct fmf identifier require/recommend, currently user needs to make sure that they specify github.com url without .git suffix. Otherwise they run into `Library 'NAME' with url 'https://github.com/beakerlib/NAME' conflicts with already fetched library from 'https://github.com/beakerlib/NAME.git'`

IMHO tmt should strip this suffix automatically so user doesn't need to care/remember whether to use suffix or not - both are allowed.

Special handling should be done only for github.com libraries because tmt itself produces the URL. Other URL are under user control so they should make sure be consistent.

**Comment by dkarpele** [comment]
Hi @lukaszachy ,
which command should be used to reproduce the issue?

**Comment by lukaszachy** [comment]
Hi @dkarpele, Just run `tmt run discover` for main.fmf containing
```
test: placeholder
framework: beakerlib

/detected:
 require: library(database/mariadb)

/explicit:
 require:
   - url: https://github.com/beakerlib/database.git
     name: /mariadb
```

The repo for backward-compatible format (library()) is created at https://github.com/psss/tmt/blob/master/tmt/beakerlib.py#L66
