### ISSUE TITLE
Ansible preparation is not runing inside the container

### ISSUE THREAD

**Issue by ZhukovGreen** [psss/tmt#621]
When running plan:
```
discover:
    how: fmf
    filter:
        - 'tag: centos8'
        - 'tag: inhibit-if-kmods-is-not-supported'
provision:
    how: container
    image: convert2rhel_centos8:latest
    pull: false
prepare:
    how: ansible
    playbook:
        - kmods.yml
```

cat kmod.yml
```
- hosts: localhost
  tasks:
    - name: Install CentOS/OL 8 packages for development
      yum:
        use_backend: dnf
        name: ["vim", "python3-devel", "git", "python3-virtualenv", "rpmlint", "rpm-build", "python3-six", "python3-nose"]
        state: present
      register: yum_res
```
the following error occurs:
```
           out: fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dnf install -y python3-dnf", "msg": "[Errno 2] No such file or directory: b'dnf'", "rc": 2}
```

It seems that ansible preparation is not running inside a container, but on the localhost.

Tested manually on
