### ISSUE TITLE
testcloud image not found

### ISSUE THREAD

**Issue by ZhukovGreen** [psss/tmt#634]
My plan config:
```yml
discover:
    how: fmf
    filter:
        - 'tag: centos8'
        - 'tag: inhibit-if-kmods-is-not-supported'
provision:
    how: virtual
    image: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
prepare:
    how: ansible
    playbook:
        - tests/integration/inhibit-if-kmods-is-not-supported/ansible/kmods.vm.yml
```
running
```bash
~/Documents/convert2rhel 
➞  tmt run plans --name kmod                                                                [git:poc/new-tmt-setup] ✖  
/var/tmp/tmt/run-302

/plans/inhibit-if-kmods-is-not-supported/centos8
    discover
        how: fmf
        directory: /home/azhukov/Documents/convert2rhel
        filter: tag: centos8
        filter: tag: inhibit-if-kmods-is-not-supported
        summary: 1 test selected
    provision
        how: virtual
        image: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
        user: root
        memory: 2048 MB
        disk: 10 GB
    finish
        summary: 0 tasks completed
Image '/var/tmp/tmt/testcloud/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2' not found.

~/Documents/convert2rhel 
➞  l /var/tmp/tmt/testcloud/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2   [git:poc/new-tmt-setup] ✖  
-rw-rw-r-- 1 azhukov azhukov 1.2G Mar 11 18:52 /var/tmp/tmt/testcloud/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
```
