### ISSUE TITLE
tmt test lint --fix - indentation not unified

### ISSUE THREAD

**Issue by mildas** [psss/tmt#695]
When a linting is fixed using `tmt test lint --fix`, strings and dicts have different indentation.

Example of `main.fmf` after lint fix (`relevancy` got converted to `adjust`):
```summary: Test calls upstream test suite.
description: |
    Runs upstream test suite against content built from the source RPM.
component:
- scap-security-guide
test: ./runtest.sh
framework: beakerlib
require:
-   url: https://github.com/beakerlib/distribution
    name: /Cleanup
- library(distribution/RpmSnapshot)
recommend:
- scap-security-guide
- python2-pytest
duration: 2h
enabled: true
adjust:
-   enabled: false
    when: distro < rhel-7
    continue: false
```

The `adjust` part has 4-space indentation, `recommend` has 2-space indentation, and `require` is mix of both.

**Comment by psss** [comment]
The following would be an ideal indentation from my point of view:

```yaml
description: |
    Runs upstream test suite against
    content built from the source RPM.
component:
  - scap-security-guide
test: ./runtest.sh
framework: beakerlib
require:
  - url: https://github.com/beakerlib/distribution
    name: /Cleanup
  - library(distribution/RpmSnapshot)
recommend:
  - scap-security-guide
  - python2-pytest
duration: 2h
enabled: true
adjust:
  - enabled: false
    when: distro < rhel-7
    continue: false
```

Basically keep 4 spaces consistently everywhere and use `␣␣-␣` for prefixing lists (space, space, dash, space).
