### ISSUE TITLE
tmt should respect user specified ansible_python_interpreter

### ISSUE THREAD

**Issue by fernflower** [psss/tmt#729]
Without tmt by ansible the playbook (sorry for downstream repo link https://gitlab.cee.redhat.com/ivasilev/rhel-upgradability-test/-/blob/tmte2e/tests/roles/upgrade/tasks/upgrade.yml#L40) successfully finishes, while tmt fails on the first task that has a user-specified ansible_python_interpreter (my bet is because it doesn't respect the setting and uses the auto one).

```
TASK [Reboot after upgrade] ****************************************************
changed: [root@10.0.207.130]

TASK [upgrade : Report status after reboot] ************************************
fatal: [root@10.0.207.130]: FAILED! => {"msg": "Failed to get information on remote file (/var/leapp/artifacts/reboot_to_upgrade_initramdisk/output.txt): Shared connection to 10.0.207.130 closed.\r\n"}

PLAY RECAP *********************************************************************
root@10.0.207.130          : ok=30   changed=26   unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

stderr (5/5 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stty: 'standard input': Inappropriate ioctl for device
[WARNING]: Consider using the yum, dnf or zypper module rather than running
'rpm'.  If you need to use command because yum, dnf or zypper is insufficient
you can add 'warn: false' to this command task or set 'command_warnings=False'
in ansible.cfg to get rid of this message.

Failed to run command 'stty cols 79; ansible-playbook --ssh-common-args="-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/ivasilev/.ssh/id_rsa" -e ansible_python_interpreter=auto -i root@10.0.207.130, /home/ivasilev/projects/leapp-upgrade-test/tests/tests.yml'.
```

The tmt plan itself:
```
summary: leapp e2e test
execute:
    how: tmt
discover:
    name: e2e
    how: fmf
    filter: 'tier: e2e'
provision:
    how: connect
    guest: 10.0.79.250
    key: ~/.ssh/id_rsa
prepare:
    how: ansible
    playbook: /home/ivasilev/projects/leapp-upgrade-test/tests/tests.yml
```
