### ISSUE TITLE
Add "--format identifiers" option for tests export

### ISSUE THREAD

**Issue by juk** [psss/tmt#804]
Having tests fmf_id's information easily available would help to use TMT's tool filtering and discoverability features in pipeline with other tools (like wow) if necessary

Proposed syntax:
`
tmt tests export --format identifiers
`

**Comment by juk** [comment]
Example of identifiers to return:
name: /distribution/ltp/lite
path: /distribution/ltp/lite
url: https://gitlab.someaddress.com/kernel
ref: kernel-sandbox

**Comment by psss** [comment]
Just to clarify, the `path` key is only used when the `fmf` metadata tree root is not identical with the git repository root. See the [fmf id specification](https://fmf.readthedocs.io/en/latest/concept.html#identifiers) for more details. Regarding the format: I think we should always provide it as a list to allow exporting mutltiple tests:

```yaml
  - url: https://gitlab.someaddress.com/kernel
    ref: kernel-sandbox
    name: /distribution/ltp/lite
  - url: https://gitlab.someaddress.com/kernel
    ref: kernel-sandbox
    name: /distribution/ltp/full
```

Should `yaml` be the output format? Or shall we default to `json`? @lukaszachy, what do you think?

**Comment by psss** [comment]
Thinking about it a bit more: Perhaps the command line should look like this?

```
tmt test export --identifiers
```

And keep the `--format` for selecting the actual format:

```
tmt test export --identifiers --format yaml
tmt test export --identifiers --format json
```

**Comment by juk** [comment]
lgtm, thank you!

**Comment by psss** [comment]
Good, then it seems we have an agreement. I'll confirm the syntax on the next hacking session but I don't expect any substantial changes. @juk, are you interested in implementing this new feature?

**Comment by psss** [comment]
@lukaszachy, the integration with `wow` should look like this?

```
tmt tests export --identifiers | wow --fmf-id=-
```

Or there should be a new dedicated option for reading fmf identifiers from a file?

```
wow --fmf-id-file=tests.json
tmt tests export --identifiers | wow --fmf-id-file=-
```

**Comment by juk** [comment]
> Good, then it seems we have an agreement. I'll confirm the syntax on the next hacking session but I don't expect any substantial changes. @juk, are you interested in implementing this new feature?
Sure, I can take this one

**Comment by psss** [comment]
Great, thank you!

**Comment by lukaszachy** [comment]
> Regarding the format: I think we should always provide it as a list to allow exporting mutltiple tests:
> 
> ```yaml
>   - url: https://gitlab.someaddress.com/kernel
>     ref: kernel-sandbox
>     name: /distribution/ltp/lite
>   - url: https://gitlab.someaddress.com/kernel
>     ref: kernel-sandbox
>     name: /distribution/ltp/full
> ```
> 
> Should `yaml` be the output format? Or shall we default to `json`? @lukaszachy, what do you think?

I'd prefer yaml's [Multi document](https://gettaurus.org/docs/YAMLTutorial/#YAML-Multi-Documents)
```yaml
url: https://gitlab.someaddress.com/kernel
ref: kernel-sandbox
name: /distribution/ltp/lite
---
url: https://gitlab.someaddress.com/kernel
ref: kernel-sandbox
name: /distribution/ltp/full
```

As for the format: yaml. If someone needs different format it can be added with `--format` option.

**Comment by lukaszachy** [comment]
> @lukaszachy, the integration with `wow` should look like this?

Currently we have `wow --fmf-id YAML_STRING` and `wow --fmf-id @file` both accepting single fmf identifier dictionary (directly or as a file content)

IMHO it makes more sense to extend fmf-id to accept `-` as STDIN and detect if multiple identifiers are present.

**Comment by psss** [comment]
> I'd prefer yaml's [Multi document](https://gettaurus.org/docs/YAMLTutorial/#YAML-Multi-Documents)

What are the advantages when compared to a list? Just quickly experimented:

```python
>>> tmt.utils.yaml_to_dict(open('/tmp/ha.yaml'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/psss/.local/lib/python3.9/site-packages/tmt/utils.py", line 744, in yaml_to_dict
    return yaml.safe_load(data)
  File "/usr/lib64/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib64/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.9/site-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "/tmp/ha.yaml", line 1, column 1
but found another document
  in "/tmp/ha.yaml", line 2, column 1
```

Is there a special way to parse such `yaml` files?

**Comment by lukaszachy** [comment]
```python
yaml.load_all()
```

I like that  you are making it explicit about accepting multiple objects. Not just by detection if the returned object is list or dict.

**Comment by lukaszachy** [comment]
So I've started with wow part and both list and multi document are supported:
`list` (of dicts):
```yaml
- url: https://gitlab.someaddress.com/kernel
  ref: kernel-sandbox
  name: /distribution/ltp/lite
- url: https://gitlab.someaddress.com/kernel
  ref: kernel-sandbox
  name: /distribution/ltp/full
```
and `multidocument` (dicts):
```yaml
url: https://gitlab.someaddress.com/kernel
ref: kernel-sandbox
name: /distribution/ltp/lite
---
url: https://gitlab.someaddress.com/kernel
ref: kernel-sandbox
name: /distribution/ltp/full
```

What to use in tmt... I'd still prefer multidocument as it  says from the beginning it can contain multiple values, but if others prefer list I wouldn't block it on that.
