### ISSUE TITLE
Parametrize discover section

### ISSUE THREAD

**Issue by phracek** [psss/tmt#814]
Use case:

Let say, I have several repositories, lie in our organization https://github.com/sclorg
All of them would like to use fmf format and work with tmt.

nowadays, the discover section can look like this:

```yaml
discover:
    how: fmf
    url: https://github.com/sclorg/<some_repository>
```

It means, that fmf file is closely connected to a specific repository.
But It would be nice and useful to parameterize it.
like

```yaml
discover:
    how: fmf
    url: https://github.com/sclorg/$REPO_NAME
```

which comes from github action like here: https://github.com/sclorg/s2i-python-container/pull/456/files#diff-77f1b582a11ff14ee5c61ecdca0b89dde806c4326362a212e4b60f1b5ecc6a02R48
Also, more parameters would be welcome like PR number and what to do when the repository is cloned. But this can be done in FMF repository but environment variable.

Adding more folks for discussion.

CC @thrix @lukaszachy 

CC @pkubat @hhorak

**Comment by lukaszachy** [comment]
Just to be sure: instead of 'tests' you mean 'url', right? https://tmt.readthedocs.io/en/stable/spec/plans.html#fmf

**Comment by phracek** [comment]
Yes, URL. Still beginner at fmf/tmt

**Comment by psss** [comment]
Looks like a nice improvement. A couple of questions come to my mind:

 * How shall we implement the substitution? Just replace any `$variable` strings? Or, to make the parsing easier, only notation like `${variable}` should be supported? Only if the environment variable is defined? Or always? Shall we use `os.path.expandvars()` for this?
 * Where should we support it? In `discover`, `provision`, `prepare` only? All keys? Or selected only?

I guess this should be relatively easy to implement.

**Comment by phracek** [comment]
> Looks like a nice improvement. A couple of questions come to my mind:
> 
>     * How shall we implement the substitution? Just replace any `$variable` strings? Or, to make the parsing easier, only notation like `${variable}` should be supported? Only if the environment variable is defined? Or always? Shall we use `os.path.expandvars()` for this?
If would say only ${variable} will be accepted and only if variable is defined. We do not provide a way to hack TMT :)
`os.path.expandvars` seems to be usable for this approach.
> 
>     * Where should we support it? In `discover`, `provision`, `prepare` only? All keys? Or selected only?
> 
I would say all of them for sure.
> 
> I guess this should be relatively easy to implement.

**Comment by jscotka** [comment]
HI,
I have fear that it is still hard to understand.
 - does that mean that ${A} will repolace this by env var from
   - cmdline  via `A=X tmt ...` 
   - or via `tmt -e A=X` 
   - or via `eviromnent: {A: X}` in plan definition?
   - or all of these are possible
  - or it will allow some jinja templates and work on this level so that
  - or it will extend yaml syntax by some substitions like: `A: X; something=${A}`
  - and also question how it should work, if it will be inside all steps, it reminds me that I have also idea to be able to pass env vars to discover or prepare phase to be able to affect preparation by env vars.

**Comment by psss** [comment]
Regarding to which environment variable sources should be applied for the substitution I'd say definitely `--environment` on command line and `environment` key in L2 metadata. This should work consistenly with how environment variables are delivered to tests.

About handing over all environment variables from the `tmt` process itself I'm not sure. This needs to be clarified. It's a bit related to the recent pull request #795 from @ZhukovGreen who might have some useful input on this topic.

**Comment by jscotka** [comment]
> Regarding to which environment variable sources should be applied for the substitution I'd say definitely `--environment` on command line and `environment` key in L2 metadata. This should work consistenly with how environment variables are delivered to tests.
> 
> About handing over all environment variables from the `tmt` process itself I'm not sure. This needs to be clarified. It's a bit related to the recent pull request #795 from @ZhukovGreen who might have some useful input on this topic.

Yes, it is more less similar to **Jenkins** handling, that you can store e.g. in some job store variables to files and next job can read it from file. in case you will deselect cleanup of jenkins workspace.
then it allows you to create env vars inside prepare phase and use it in tests (execute) phase then.

Or another possibility is to use some simlar syntax what has **ansible**, something like registering output of something to variable and be able then to use this variable inside ansible recipe.

**Comment by ZhukovGreen** [comment]
Hey guys, just some alternative view. Now you're introducing to read env vars inside fmf format as a tool to adjust the metadata. However, there is an existing mechanism to adjust the metadata via https://tmt.readthedocs.io/en/stable/spec/core.html#adjust. So let's try to think also how it might look like if follow the existing mechanism.

I'd see it as follow:
```yaml
discover:
    how: fmf
    url: https://github.com/sclorg/some_default_repository
adjust:
    - discover:
          url: https://github.com/sclorg/some_repository_a
      when:
          lookup("env", "GH_REPO") == https://github.com/sclorg/some_repository_a
    - discover:
          url: https://github.com/sclorg/some_repository_b
      when:
          lookup("env", "GH_REPO") == https://github.com/sclorg/some_repository_b
```

It seems to me a bit dirty, but maybe you can adopt a cleaner way.

Also, it is fair to mention that docker-compose config for example has the possibility to use env vars inside the config (https://docs.docker.com/compose/environment-variables/). But if this feature would be available in the tmt, then what is the reason to use `adjust`?
