### ISSUE TITLE
AND | OR rule in adjust -> when parameter 

### ISSUE THREAD

**Issue by ZhukovGreen** [psss/tmt#839]
I am trying to ensure the test will be running only for relevant distros with the help of the following config.

```yaml
summary: check-custom-repo
tag+:
  - centos7
  - centos8
  - oracle7
  - oracle8
  - check-custom-repo
adjust:
  enabled: false
  when: >
    distro != centos-7 or
    distro != centos-8 or
    distro != oracle-7 or
    distro != oracle-8
```

However, this definition is not working as expected and the test is filtered out all the time. i was looking to https://fmf.readthedocs.io/en/latest/context.html#syntax and from my point of view the syntax complies. However, if I run the following command:
```
tmt --context distro=centos-7 run plan --name /plans/integration/check-custom-repo/vm_centos8/good -vvvddd
```
no tests selected
