### ISSUE TITLE
Feature environment-file-url. Load env vars from a file located at url

### ISSUE THREAD

**Issue by ZhukovGreen** [psss/tmt#840]
Follow up from #795 . I have a problem of introducing environment file which contains  secrets for the case when tests are executed in the remote environment. For local execution environment-file is fine. 

In our case when running test on testing farm or via packit our main plan would look like this:
```yaml
execute:
    how: tmt
discover:
    how: fmf
prepare:
    - name: main preparation step
      how: ansible
      playbook: tests/ansible_collections/main.yml
environment-file:
  - .env
adjust:
  - environment-file-:
    - .env
    when: distro != ""
  - environment-file-url:
      - https://some-repo-with-secrets/secrets.yaml
      - https://some-repo-with-secrets/.env
    when: distro != ""
```

By using this `when: distro != ""` I am trying to use what we have in the packet CI. Packit specifies distro context, so if distro is not empty, then I know that the tmt run executed in the CI, so I need env vars from url

**Comment by ZhukovGreen** [comment]
I'd like to make a MR to address this ticket. Are you ok with that approach?

**Comment by ZhukovGreen** [comment]
@psss @lachmanfrantisek @thrix @lukaszachy ^^^

**Comment by psss** [comment]
> Packit specifies distro context, so if distro is not empty, then I know that the tmt run executed in the CI, so I need env vars from url

In order to detect when a `tmt` plan is executed in packit / testing farm I would suggest using the `trigger` dimension of the context:

```yaml
adjust:
    environment-file: ...
    when: trigger == commit
```

See the [trigger](https://tmt.readthedocs.io/en/stable/spec/context.html#trigger) documentation for the definition of the dimension.
