### ISSUE TITLE
HW requirements - more than one disk

### ISSUE THREAD

**Issue by happz** [psss/tmt#893]
There are teams that require more than the root disk. For example, the following `provision.fmf` file:

```yaml
---

standard-inventory-qcow2:
  qemu:
    m: 10G
    drive:
      - size: 10737418240
      - size: 10737418240
      - size: 1073741824
```

`m` (as in "memory") we can already handle, with `memory: 10 GiB`, but what about the disk storage? It turns out the teams are currently blocked by the lack of language to express this need when it comes to migrating to TFT (and Artemis). Any ideas on how to express the fact a test needs additional "disks"? Let's put aside the implementation part of the problem.

Let's say we have such an HW requirement:

```yaml
disk
  space: ">=20 GiB"
memory: ">= 10 GiB"
cpu:
  cores: 8
```

How to extend the `disk` key to allow "moar disks!", leaving door open for future enhancements?

**Comment by psss** [comment]
What about allowing the `disk` key to be a dictionary or a list of dictionaries?

```yaml
disk:
  - space: ">= 20 GB"
  - space: ">= 2 GB"
```

Does that look extensible enough? Or we need something more sophisticated?

**Comment by happz** [comment]
> What about allowing the `disk` key to be a dictionary or a list of dictionaries?
> 
> ```yaml
> disk:
>   - space: ">= 20 GB"
>   - space: ">= 2 GB"
> ```
> 
> Does that look extensible enough? Or we need something more sophisticated?

LGTM, at the first glance. I did no extensive research so far, but I'd say this leaves enough space for new additions, e.g. this could be possible (not saying it's something `tmt` is interested in doing, but it would be possible to express):

```yaml
disk:
  - space: ">= 20 GB"
    volume_group: vg0
    mount: "/mnt/foo"
  - space: ">= 2 GB"
    volume_group: vg1
    mount: "/mnt/bar"
```

So adding more attributes should be possible. The only issue I see is the change of the type of `disk`, from `str` to `List[Dict[...]]`, but we're still in the land of prototypes.
