### ISSUE TITLE
HW requirements - multiple NIC

### ISSUE THREAD

**Issue by fernflower** [psss/tmt#894]
Some of oamg tests require guests with multiple network interfaces. 
In beaker this can be specified with `<key_value key="NR_ETH" value="2"/>`
We'd love to be able to run those tests with tmt as well.

**Comment by psss** [comment]
This sounds like for certain provision methods, such as `beaker` for example, there could be an extra key dedicated for providing a free-form key-value information. I don't think we can (or should) provide an extra syntax for each and every use case which users will run into. Provision plugins which would not support there extra values would just ignore the information. Does that make sense?

**Comment by psss** [comment]
Summary from today's hacking session: Let's define a new `network` attribute which would be a list of dictionaries describing the desired network interface(s):

```yaml
# single interface
network:
  - type: eth

# multiple interfaces
network:
  - type: eth
  - type: eth
    vendor: name
```

@fernflower, could you possibly provide some more real-life examples of the keys which would be useful to specify the interface?
