### ISSUE TITLE
Get rid of unstandard `=~` for regular expression matching

### ISSUE THREAD

**Issue by thrix** [psss/tmt#909]
In:

https://github.com/psss/tmt/pull/895

the proposal is to use `=~` for pattern matching. I am not sure we need it, it is not very standard in yaml, I believe it will cause confusion. Also there is the question about the leading "space" bringing more `ambiguity`.

```
        network:
          - type: eth
            vendor-name: =~ Broadcom.*
            device-name: =~ NetXtreme II BCM.*
```

I have following proposals:

1. Use regular expression always for these fields, add leading `^` and ending `$` characters automatically

```
        network:
          - type: eth
            vendor-name: Broadcom.*
            device-name: NetXtreme II BCM.*
```

2. Use rather a flag to signalize this is a regex:

```
        network:
          - type: eth
            vendor-name: Broadcom.*
                regex: true
            device-name: NetXtreme II BCM.*
                regex: true
```
