### ISSUE TITLE
Add support for enabling verbose mode in fmf file

### ISSUE THREAD

**Issue by phracek** [psss/tmt#937]
Nowadays, my FMF file looks like this:

```
prepare:
    - name: Enable repositories and prepare machine for tests
      how: ansible
      playbook:
        - tmt-testing-plan-rhel7.yml

```

It would be nice to add there a possibility like:
```
prepare:
    - name: Enable repositories and prepare machine for tests
      how: ansible
      playbook:
        - tmt-testing-plan-rhel7.yml
      verbose: true

```

in order to allow verbose mode for ansible playbook

**Comment by psss** [comment]
Perhaps, I would suggest to use integer to specify the verbosity level as `ansible` has a lot of debug levels.

**Comment by psss** [comment]
Should be relatively easy to implement by extending the `ansible()` method:

https://github.com/psss/tmt/blob/980c0fefcfd93ff5b1417449fe7f63ed16faef23/tmt/steps/provision/__init__.py#L398

And override the default `_ansible_verbosity()` detected from options. @ZelenyMartin, @dkarpele, fyi.

**Comment by psss** [comment]
We've discussed the implementation on today's hacking session with the following proposal: Instead of introducing a single key for raising the verbosity what about rather adding a support for providing extra ansible arguments? The config could look like this:

```yaml
prepare:
  - how: ansible
    playbook: tmt-testing-plan-rhel7.yml
    extra-args: -vvvvvvv
```

This would be a bit more extensible for possible other user parameters. @phracek, what do you think? Plus we'd like to clarify with you: After enabling the
