### ISSUE TITLE
ability to define and distinguish multiple sets of tests in the discover step

### ISSUE THREAD

**Issue by sopos** [psss/tmt#945]
Implement an option to specify mupliple sets in the discover to be able to use them differently.

```yaml
discover:
- how: fmf
  filter: tag:setup
  name: setups
- how: fmf
  filter: tag:!setup
  name: tests
prepare:
- how: tmt
  what: setups
execute:
- how: tmt
  what: tests
```
