### ISSUE TITLE
Execute's environment doesn't override test's

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#946]
Documentation says that [environemnt](https://tmt.readthedocs.io/en/latest/spec/plans.html#environment) attribute:
`Specifies environment variables available in all steps. Plugins need to include these environment variables while running commands or other programs. These environment variables should override L1 environment if present.`

I read it that you can specify 'environment' even in step and it should be used from there, but (updated reproducer):
```
/reproducer:
    test: declare -p FOO
    environment:
        FOO: test
/plan:
    execute:
        how: tmt
        environment:
            FOO: exec
    discover:
        how: fmf
    environment:
        FOO: plan
```
`$ tmt run -avvv provision -h local` -> `content: declare -x FOO="plan"`
