### ISSUE TITLE
Support beakerlib tests as prepare scripts

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#969]
While tmt supports ansible and shell as prepare plugins there are a lot of "tests" written in beakerlib which are setup/preparation steps in reality. If tmt could execute tmt tests as part of the prepare step it would be great. 

It could be very similar to discover:fmf
Needs to support order, require/recommend, libraries, remote repo fetching.

**Comment by lukaszachy** [comment]
Related #945

**Comment by psss** [comment]
Interesting idea. Should be useful, especially from the backward-compatibility and fluent transition point of view.

> IMHO worth of _new plugin_ to keep `how:shell` simple as it is now.

Makes sense, agreed.

**Comment by kkaarreell** [comment]
Hello,
pasting below my use case:

Plan 1 for testing upstream keylime bits that are installed with /setup/install_upstream_keylime
```
prepare:
  how: fmf
  test:
   - /setup/configure_tpm_emulator
   - /setup/install_upstream_keylime
discover:
  how: fmf
  test:
   - "/functional/.*"
```
Plan 2 for testing distribution keylime RPMs, keylime is installed since each test have keylime in requires.
```
prepare:
  how: fmf
  test:
   - /setup/configure_tpm_emulator
discover:
  how: fmf
  test:
   - "/functional/.*"
```
So far I was using this
```
Plan 1 for testing upstream keylime bits that are installed with /setup/install_upstream_keylime
```
discover:
  how: fmf
  test:
   - /setup/configure_tpm_emulator
   - /setup/install_upstream_keylime
   - "/functional/.*"
```
but since all requires are installed at the beginning keylime was already installed when /setup/install_upstream_keylime task was executed. Now, there are definitely some workarounds here, e.g. I can remove keylime from requires and install it in the test plan prepare step (but that would break test for someone not using my plan) or I could remove keylime in the /setup/install_upstream_keylime test. However, the problem is more generic. If a "test" is e.g. configuring an additional repository (like buildroot) then we need to have test requires installed from that repository and therefore it would be handy to have the setup task executed in Prepare step. And while we can execute shell scripts, as described in this issue it is handy to benefit from various asserts, consume attached logs etc.

**Comment by sopos** [comment]
While this should be possible for _prepare_ it should be possible for _finish_ as well as one might want to process some gathered data at the end.
It also means that even the _prepare_ / _finish_ tests should undergo some kind of discover processing.

I could imagine something like this:

```yaml
discover:
  - how: fmf
    url: ...
    tests:
      - /setup/some_service
    name: SETUP
  - how: fmf
    url: ...
    filter: tag:!setup
    name: TEST
  - how: fmf
    url: ...
    tests:
      - /report/some_service_output_processing
    name: REPORT
prepare:
    how: tmt
    what: SETUP
execute:
    how: tmt
    what: TEST
finish:
    how: tmt
    what: REPORT
```

**Comment by kkaarreell** [comment]
It is not strictly related but also prepare step logging should be improved and possibly even included in jUnit XML. Having such logs imported e.g. in ReportPortal in a structured manner would mean users can benefit from RP features like AutoAnalysis.

**Comment by sopos** [comment]
I'm rephrasing my idea with the currently proposed way:

```yaml
discover:
  - how: fmf
    url: ...
    filter: tag:!setup
prepare:
    how: fmf
    url: ...
    tests:
      - /setup/some_service
execute:
    how: tmt
finish:
    how: fmf
    url: ...
    tests:
      - /report/some_service_output_processing
```

The only thing I see a bit misleading is that the "execution" in the _prepare_ / _finish_ steps is the _tmt_ one while I have to specify _fmf_ as I need to discover it in an _fmf_ way.
In other words, I'm doing `how: fmf` because of the discovery and `how: tmt` because of the execution while one is explicit and the other one is implicit. Would I ever want something else than `how: tmt` for the execution?
