### ISSUE TITLE
adjust should also work for prepare steps

### ISSUE THREAD

**Issue by thrix** [psss/tmt#972]
Seems this does not work right?

```
prepare:    
  how: install    
  package: epel-release    
  adjust:    
    when: distro == centos-8    
```

I would like to run a specific prepare step only on some OSes.

**Comment by psss** [comment]
The correct `adjust` syntax would be this:

```yaml
summary: Basic smoke test
execute:
    script: tmt --help
adjust:
    prepare:
        how: install
        package: epel-release
    when: distro == centos-8
```

This seems to be working just fine:

```
> tmt plan show
/plans/example
     summary Basic smoke test
     execute 
         how tmt
      script tmt --help
     enabled true

> tmt -c distro=centos-8 plan show
/plans/example
     summary Basic smoke test
     prepare 
         how install
     package epel-release
     exclude 
     missing fail
     execute 
         how tmt
      script tmt --help
     enabled true
     context distro: ['centos-8']
```
